name: Deploy Flask App

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: self-hosted
        env:
            DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
        steps:
            
            - name: checkout code
              uses: actions/checkout@v4

            - name: pull latest image
              run: docker compose pull

            - name: stop old container
              run: docker compose down

            - name: deploy with docker compose
              run: docker compose up -d --build