name: Portfolio

on:
    
    workflow_dispatch:
        inputs:
            release_note:
                description: 'Optional deployment notes'
                type: string
                required: false
                default: 'Triggered by Atharv'

permissions:
    contents: read
    pages: write
    id-token: write
    
jobs:
    deploy:
        runs-on: ubuntu-latest

        environment:
            name: github-pages
            url: ${{steps.deployment.outputs.page_url}}

        steps:
          - name: Code checkout
            uses: actions/checkout@v4

          - name: setup github pages for web hosting
            uses: actions/configure-pages@v5

          - name: uploading static artifacts or packing the code
            uses: actions/upload-pages-artifact@v3
            with:
                path: '.'

          - name: deploying on pages
            id: deployment
            uses: actions/deploy-pages@v4
